// src/lib/country.ts

export interface CountryData {
  code: string;
  flag: string;
  name: string;
}

export const countryMap: Record<string, CountryData> = {
    // --- POPULAR / COMMON ---
    "PAKISTAN": { code: "PK", flag: "🇵🇰", name: "Pakistan" },
    "PK": { code: "PK", flag: "🇵🇰", name: "Pakistan" },
    "INDIA": { code: "IN", flag: "🇮🇳", name: "India" },
    "IN": { code: "IN", flag: "🇮🇳", name: "India" }, 
    "BANGLADESH": { code: "BD", flag: "🇧🇩", name: "Bangladesh" },
    "BD": { code: "BD", flag: "🇧🇩", name: "Bangladesh" },
    "USA": { code: "US", flag: "🇺🇸", name: "United States" },
    "UNITED STATES": { code: "US", flag: "🇺🇸", name: "United States" },
    "US": { code: "US", flag: "🇺🇸", name: "United States" },
    "CANADA": { code: "CA", flag: "🇨🇦", name: "Canada" },
    "CA": { code: "CA", flag: "🇨🇦", name: "Canada" },
    "UK": { code: "GB", flag: "🇬🇧", name: "United Kingdom" },
    "UNITED KINGDOM": { code: "GB", flag: "🇬🇧", name: "United Kingdom" },
    "GB": { code: "GB", flag: "🇬🇧", name: "United Kingdom" },
    "GERMANY": { code: "DE", flag: "🇩🇪", name: "Germany" },
    "DE": { code: "DE", flag: "🇩🇪", name: "Germany" },
    "FRANCE": { code: "FR", flag: "🇫🇷", name: "France" },
    "FR": { code: "FR", flag: "🇫🇷", name: "France" },
    "UAE": { code: "AE", flag: "🇦🇪", name: "UAE" },
    "UNITED ARAB EMIRATES": { code: "AE", flag: "🇦🇪", name: "UAE" },
    "DUBAI": { code: "AE", flag: "🇦🇪", name: "UAE" },
    "AE": { code: "AE", flag: "🇦🇪", name: "UAE" },
    "SAUDI ARABIA": { code: "SA", flag: "🇸🇦", name: "Saudi Arabia" },
    "SA": { code: "SA", flag: "🇸🇦", name: "Saudi Arabia" },
    "AUSTRALIA": { code: "AU", flag: "🇦🇺", name: "Australia" },
    "AU": { code: "AU", flag: "🇦🇺", name: "Australia" },
    "NEW ZEALAND": { code: "NZ", flag: "🇳🇿", name: "New Zealand" },
    "NZ": { code: "NZ", flag: "🇳🇿", name: "New Zealand" },
    "SINGAPORE": { code: "SG", flag: "🇸🇬", name: "Singapore" },
    "SG": { code: "SG", flag: "🇸🇬", name: "Singapore" },
    "JAPAN": { code: "JP", flag: "🇯🇵", name: "Japan" },
    "JP": { code: "JP", flag: "🇯🇵", name: "Japan" },
    "CHINA": { code: "CN", flag: "🇨🇳", name: "China" },
    "CN": { code: "CN", flag: "🇨🇳", name: "China" },
    "PHILIPPINES": { code: "PH", flag: "🇵🇭", name: "Philippines" },
    "PH": { code: "PH", flag: "🇵🇭", name: "Philippines" },
    "VIETNAM": { code: "VN", flag: "🇻🇳", name: "Vietnam" },
    "VN": { code: "VN", flag: "🇻🇳", name: "Vietnam" },
    "INDONESIA": { code: "ID", flag: "🇮🇩", name: "Indonesia" },
    "ID": { code: "ID", flag: "🇮🇩", name: "Indonesia" },
    "BRAZIL": { code: "BR", flag: "🇧🇷", name: "Brazil" },
    "BR": { code: "BR", flag: "🇧🇷", name: "Brazil" },
    "ARGENTINA": { code: "AR", flag: "🇦🇷", name: "Argentina" },
    "AR": { code: "AR", flag: "🇦🇷", name: "Argentina" },
    "NIGERIA": { code: "NG", flag: "🇳🇬", name: "Nigeria" },
    "NG": { code: "NG", flag: "🇳🇬", name: "Nigeria" },
    "EGYPT": { code: "EG", flag: "🇪🇬", name: "Egypt" },
    "EG": { code: "EG", flag: "🇪🇬", name: "Egypt" },
    "SOUTH AFRICA": { code: "ZA", flag: "🇿🇦", name: "South Africa" },
    "ZA": { code: "ZA", flag: "🇿🇦", name: "South Africa" },
    "NORWAY": { code: "NO", flag: "🇳🇴", name: "Norway" },
    "NO": { code: "NO", flag: "🇳🇴", name: "Norway" },

    // --- REST OF THE WORLD (A-Z) ---
    "AFGHANISTAN": { code: "AF", flag: "🇦🇫", name: "Afghanistan" },
    "AF": { code: "AF", flag: "🇦🇫", name: "Afghanistan" },
    "ALBANIA": { code: "AL", flag: "🇦🇱", name: "Albania" },
    "AL": { code: "AL", flag: "🇦🇱", name: "Albania" },
    "ALGERIA": { code: "DZ", flag: "🇩🇿", name: "Algeria" },
    "DZ": { code: "DZ", flag: "🇩🇿", name: "Algeria" },
    "ANDORRA": { code: "AD", flag: "🇦🇩", name: "Andorra" },
    "AD": { code: "AD", flag: "🇦🇩", name: "Andorra" },
    "ANGOLA": { code: "AO", flag: "🇦🇴", name: "Angola" },
    "AO": { code: "AO", flag: "🇦🇴", name: "Angola" },
    "ANTIGUA": { code: "AG", flag: "🇦🇬", name: "Antigua and Barbuda" },
    "AG": { code: "AG", flag: "🇦🇬", name: "Antigua and Barbuda" },
    "ARMENIA": { code: "AM", flag: "🇦🇲", name: "Armenia" },
    "AM": { code: "AM", flag: "🇦🇲", name: "Armenia" },
    "AUSTRIA": { code: "AT", flag: "🇦🇹", name: "Austria" },
    "AT": { code: "AT", flag: "🇦🇹", name: "Austria" },
    "AZERBAIJAN": { code: "AZ", flag: "🇦🇿", name: "Azerbaijan" },
    "AZ": { code: "AZ", flag: "🇦🇿", name: "Azerbaijan" },
    "BAHAMAS": { code: "BS", flag: "🇧🇸", name: "Bahamas" },
    "BS": { code: "BS", flag: "🇧🇸", name: "Bahamas" },
    "BAHRAIN": { code: "BH", flag: "🇧🇭", name: "Bahrain" },
    "BH": { code: "BH", flag: "🇧🇭", name: "Bahrain" },
    "BARBADOS": { code: "BB", flag: "🇧🇧", name: "Barbados" },
    "BB": { code: "BB", flag: "🇧🇧", name: "Barbados" },
    "BELARUS": { code: "BY", flag: "🇧🇾", name: "Belarus" },
    "BY": { code: "BY", flag: "🇧🇾", name: "Belarus" },
    "BELGIUM": { code: "BE", flag: "🇧🇪", name: "Belgium" },
    "BE": { code: "BE", flag: "🇧🇪", name: "Belgium" },
    "BELIZE": { code: "BZ", flag: "🇧🇿", name: "Belize" },
    "BZ": { code: "BZ", flag: "🇧🇿", name: "Belize" },
    "BENIN": { code: "BJ", flag: "🇧🇯", name: "Benin" },
    "BJ": { code: "BJ", flag: "🇧🇯", name: "Benin" },
    "BHUTAN": { code: "BT", flag: "🇧🇹", name: "Bhutan" },
    "BT": { code: "BT", flag: "🇧🇹", name: "Bhutan" },
    "BOLIVIA": { code: "BO", flag: "🇧🇴", name: "Bolivia" },
    "BO": { code: "BO", flag: "🇧🇴", name: "Bolivia" },
    "BOSNIA": { code: "BA", flag: "🇧🇦", name: "Bosnia and Herzegovina" },
    "BA": { code: "BA", flag: "🇧🇦", name: "Bosnia and Herzegovina" },
    "BOTSWANA": { code: "BW", flag: "🇧🇼", name: "Botswana" },
    "BW": { code: "BW", flag: "🇧🇼", name: "Botswana" },
    "BRUNEI": { code: "BN", flag: "🇧🇳", name: "Brunei" },
    "BN": { code: "BN", flag: "🇧🇳", name: "Brunei" },
    "BULGARIA": { code: "BG", flag: "🇧🇬", name: "Bulgaria" },
    "BG": { code: "BG", flag: "🇧🇬", name: "Bulgaria" },
    "BURKINA FASO": { code: "BF", flag: "🇧🇫", name: "Burkina Faso" },
    "BF": { code: "BF", flag: "🇧🇫", name: "Burkina Faso" },
    "BURUNDI": { code: "BI", flag: "🇧🇮", name: "Burundi" },
    "BI": { code: "BI", flag: "🇧🇮", name: "Burundi" },
    "CAMBODIA": { code: "KH", flag: "🇰🇭", name: "Cambodia" },
    "KH": { code: "KH", flag: "🇰🇭", name: "Cambodia" },
    "CAMEROON": { code: "CM", flag: "🇨🇲", name: "Cameroon" },
    "CM": { code: "CM", flag: "🇨🇲", name: "Cameroon" },
    "CAPE VERDE": { code: "CV", flag: "🇨🇻", name: "Cape Verde" },
    "CV": { code: "CV", flag: "🇨🇻", name: "Cape Verde" },
    "CHILE": { code: "CL", flag: "🇨🇱", name: "Chile" },
    "CL": { code: "CL", flag: "🇨🇱", name: "Chile" },
    "COLOMBIA": { code: "CO", flag: "🇨🇴", name: "Colombia" },
    "CO": { code: "CO", flag: "🇨🇴", name: "Colombia" },
    "COMOROS": { code: "KM", flag: "🇰🇲", name: "Comoros" },
    "KM": { code: "KM", flag: "🇰🇲", name: "Comoros" },
    "COSTA RICA": { code: "CR", flag: "🇨🇷", name: "Costa Rica" },
    "CR": { code: "CR", flag: "🇨🇷", name: "Costa Rica" },
    "CROATIA": { code: "HR", flag: "🇭🇷", name: "Croatia" },
    "HR": { code: "HR", flag: "🇭🇷", name: "Croatia" },
    "CUBA": { code: "CU", flag: "🇨🇺", name: "Cuba" },
    "CU": { code: "CU", flag: "🇨🇺", name: "Cuba" },
    "CYPRUS": { code: "CY", flag: "🇨🇾", name: "Cyprus" },
    "CY": { code: "CY", flag: "🇨🇾", name: "Cyprus" },
    "CZECH REPUBLIC": { code: "CZ", flag: "🇨🇿", name: "Czech Republic" },
    "CZ": { code: "CZ", flag: "🇨🇿", name: "Czech Republic" },
    "DENMARK": { code: "DK", flag: "🇩🇰", name: "Denmark" },
    "DK": { code: "DK", flag: "🇩🇰", name: "Denmark" },
    "DJIBOUTI": { code: "DJ", flag: "🇩🇯", name: "Djibouti" },
    "DJ": { code: "DJ", flag: "🇩🇯", name: "Djibouti" },
    "DOMINICA": { code: "DM", flag: "🇩🇲", name: "Dominica" },
    "DM": { code: "DM", flag: "🇩🇲", name: "Dominica" },
    "DOMINICAN REPUBLIC": { code: "DO", flag: "🇩🇴", name: "Dominican Republic" },
    "DO": { code: "DO", flag: "🇩🇴", name: "Dominican Republic" },
    "ECUADOR": { code: "EC", flag: "🇪🇨", name: "Ecuador" },
    "EC": { code: "EC", flag: "🇪🇨", name: "Ecuador" },
    "EL SALVADOR": { code: "SV", flag: "🇸🇻", name: "El Salvador" },
    "SV": { code: "SV", flag: "🇸🇻", name: "El Salvador" },
    "ESTONIA": { code: "EE", flag: "🇪🇪", name: "Estonia" },
    "EE": { code: "EE", flag: "🇪🇪", name: "Estonia" },
    "ETHIOPIA": { code: "ET", flag: "🇪🇹", name: "Ethiopia" },
    "ET": { code: "ET", flag: "🇪🇹", name: "Ethiopia" },
    "FIJI": { code: "FJ", flag: "🇫🇯", name: "Fiji" },
    "FJ": { code: "FJ", flag: "🇫🇯", name: "Fiji" },
    "FINLAND": { code: "FI", flag: "🇫🇮", name: "Finland" },
    "FI": { code: "FI", flag: "🇫🇮", name: "Finland" },
    "GABON": { code: "GA", flag: "🇬🇦", name: "Gabon" },
    "GA": { code: "GA", flag: "🇬🇦", name: "Gabon" },
    "GAMBIA": { code: "GM", flag: "🇬🇲", name: "Gambia" },
    "GM": { code: "GM", flag: "🇬🇲", name: "Gambia" },
    "GEORGIA": { code: "GE", flag: "🇬🇪", name: "Georgia" },
    "GE": { code: "GE", flag: "🇬🇪", name: "Georgia" },
    "GHANA": { code: "GH", flag: "🇬🇭", name: "Ghana" },
    "GH": { code: "GH", flag: "🇬🇭", name: "Ghana" },
    "GREECE": { code: "GR", flag: "🇬🇷", name: "Greece" },
    "GR": { code: "GR", flag: "🇬🇷", name: "Greece" },
    "GRENADA": { code: "GD", flag: "🇬🇩", name: "Grenada" },
    "GD": { code: "GD", flag: "🇬🇩", name: "Grenada" },
    "GUATEMALA": { code: "GT", flag: "🇬🇹", name: "Guatemala" },
    "GT": { code: "GT", flag: "🇬🇹", name: "Guatemala" },
    "GUINEA": { code: "GN", flag: "🇬🇳", name: "Guinea" },
    "GN": { code: "GN", flag: "🇬🇳", name: "Guinea" },
    "GUYANA": { code: "GY", flag: "🇬🇾", name: "Guyana" },
    "GY": { code: "GY", flag: "🇬🇾", name: "Guyana" },
    "HAITI": { code: "HT", flag: "🇭🇹", name: "Haiti" },
    "HT": { code: "HT", flag: "🇭🇹", name: "Haiti" },
    "HONDURAS": { code: "HN", flag: "🇭🇳", name: "Honduras" },
    "HN": { code: "HN", flag: "🇭🇳", name: "Honduras" },
    "HUNGARY": { code: "HU", flag: "🇭🇺", name: "Hungary" },
    "HU": { code: "HU", flag: "🇭🇺", name: "Hungary" },
    "ICELAND": { code: "IS", flag: "🇮🇸", name: "Iceland" },
    "IS": { code: "IS", flag: "🇮🇸", name: "Iceland" },
    "IRAN": { code: "IR", flag: "🇮🇷", name: "Iran" },
    "IR": { code: "IR", flag: "🇮🇷", name: "Iran" },
    "IRAQ": { code: "IQ", flag: "🇮🇶", name: "Iraq" },
    "IQ": { code: "IQ", flag: "🇮🇶", name: "Iraq" },
    "IRELAND": { code: "IE", flag: "🇮🇪", name: "Ireland" },
    "IE": { code: "IE", flag: "🇮🇪", name: "Ireland" },
    "ISRAEL": { code: "IL", flag: "🇮🇱", name: "Israel" },
    "IL": { code: "IL", flag: "🇮🇱", name: "Israel" },
    "ITALY": { code: "IT", flag: "🇮🇹", name: "Italy" },
    "IT": { code: "IT", flag: "🇮🇹", name: "Italy" },
    "JAMAICA": { code: "JM", flag: "🇯🇲", name: "Jamaica" },
    "JM": { code: "JM", flag: "🇯🇲", name: "Jamaica" },
    "JORDAN": { code: "JO", flag: "🇯🇴", name: "Jordan" },
    "JO": { code: "JO", flag: "🇯🇴", name: "Jordan" },
    "KAZAKHSTAN": { code: "KZ", flag: "🇰🇿", name: "Kazakhstan" },
    "KZ": { code: "KZ", flag: "🇰🇿", name: "Kazakhstan" },
    "KENYA": { code: "KE", flag: "🇰🇪", name: "Kenya" },
    "KE": { code: "KE", flag: "🇰🇪", name: "Kenya" },
    "KUWAIT": { code: "KW", flag: "🇰🇼", name: "Kuwait" },
    "KW": { code: "KW", flag: "🇰🇼", name: "Kuwait" },
    "KYRGYZSTAN": { code: "KG", flag: "🇰🇬", name: "Kyrgyzstan" },
    "KG": { code: "KG", flag: "🇰🇬", name: "Kyrgyzstan" },
    "LAOS": { code: "LA", flag: "🇱🇦", name: "Laos" },
    "LA": { code: "LA", flag: "🇱🇦", name: "Laos" },
    "LATVIA": { code: "LV", flag: "🇱🇻", name: "Latvia" },
    "LV": { code: "LV", flag: "🇱🇻", name: "Latvia" },
    "LEBANON": { code: "LB", flag: "🇱🇧", name: "Lebanon" },
    "LB": { code: "LB", flag: "🇱🇧", name: "Lebanon" },
    "LIBYA": { code: "LY", flag: "🇱🇾", name: "Libya" },
    "LY": { code: "LY", flag: "🇱🇾", name: "Libya" },
    "LITHUANIA": { code: "LT", flag: "🇱🇹", name: "Lithuania" },
    "LT": { code: "LT", flag: "🇱🇹", name: "Lithuania" },
    "LUXEMBOURG": { code: "LU", flag: "🇱🇺", name: "Luxembourg" },
    "LU": { code: "LU", flag: "🇱🇺", name: "Luxembourg" },
    "MADAGASCAR": { code: "MG", flag: "🇲🇬", name: "Madagascar" },
    "MG": { code: "MG", flag: "🇲🇬", name: "Madagascar" },
    "MALAYSIA": { code: "MY", flag: "🇲🇾", name: "Malaysia" },
    "MY": { code: "MY", flag: "🇲🇾", name: "Malaysia" },
    "MALDIVES": { code: "MV", flag: "🇲🇻", name: "Maldives" },
    "MV": { code: "MV", flag: "🇲🇻", name: "Maldives" },
    "MALI": { code: "ML", flag: "🇲🇱", name: "Mali" },
    "ML": { code: "ML", flag: "🇲🇱", name: "Mali" },
    "MALTA": { code: "MT", flag: "🇲🇹", name: "Malta" },
    "MT": { code: "MT", flag: "🇲🇹", name: "Malta" },
    "MEXICO": { code: "MX", flag: "🇲🇽", name: "Mexico" },
    "MX": { code: "MX", flag: "🇲🇽", name: "Mexico" },
    "MOLDOVA": { code: "MD", flag: "🇲🇩", name: "Moldova" },
    "MD": { code: "MD", flag: "🇲🇩", name: "Moldova" },
    "MONACO": { code: "MC", flag: "🇲🇨", name: "Monaco" },
    "MC": { code: "MC", flag: "🇲🇨", name: "Monaco" },
    "MONGOLIA": { code: "MN", flag: "🇲🇳", name: "Mongolia" },
    "MN": { code: "MN", flag: "🇲🇳", name: "Mongolia" },
    "MONTENEGRO": { code: "ME", flag: "🇲🇪", name: "Montenegro" },
    "ME": { code: "ME", flag: "🇲🇪", name: "Montenegro" },
    "MOROCCO": { code: "MA", flag: "🇲🇦", name: "Morocco" },
    "MA": { code: "MA", flag: "🇲🇦", name: "Morocco" },
    "MYANMAR": { code: "MM", flag: "🇲🇲", name: "Myanmar" },
    "MM": { code: "MM", flag: "🇲🇲", name: "Myanmar" },
    "NAMIBIA": { code: "NA", flag: "🇳🇦", name: "Namibia" },
    "NA": { code: "NA", flag: "🇳🇦", name: "Namibia" },
    "NEPAL": { code: "NP", flag: "🇳🇵", name: "Nepal" },
    "NP": { code: "NP", flag: "🇳🇵", name: "Nepal" },
    "NETHERLANDS": { code: "NL", flag: "🇳🇱", name: "Netherlands" },
    "NL": { code: "NL", flag: "🇳🇱", name: "Netherlands" },
    "NICARAGUA": { code: "NI", flag: "🇳🇮", name: "Nicaragua" },
    "NI": { code: "NI", flag: "🇳🇮", name: "Nicaragua" },
    "NIGER": { code: "NE", flag: "🇳🇪", name: "Niger" },
    "NE": { code: "NE", flag: "🇳🇪", name: "Niger" },
    "NORTH KOREA": { code: "KP", flag: "🇰🇵", name: "North Korea" },
    "KP": { code: "KP", flag: "🇰🇵", name: "North Korea" },
    "OMAN": { code: "OM", flag: "🇴🇲", name: "Oman" },
    "OM": { code: "OM", flag: "🇴🇲", name: "Oman" },
    "PANAMA": { code: "PA", flag: "🇵🇦", name: "Panama" },
    "PA": { code: "PA", flag: "🇵🇦", name: "Panama" },
    "PARAGUAY": { code: "PY", flag: "🇵🇾", name: "Paraguay" },
    "PY": { code: "PY", flag: "🇵🇾", name: "Paraguay" },
    "PERU": { code: "PE", flag: "🇵🇪", name: "Peru" },
    "PE": { code: "PE", flag: "🇵🇪", name: "Peru" },
    "POLAND": { code: "PL", flag: "🇵🇱", name: "Poland" },
    "PL": { code: "PL", flag: "🇵🇱", name: "Poland" },
    "PORTUGAL": { code: "PT", flag: "🇵🇹", name: "Portugal" },
    "PT": { code: "PT", flag: "🇵🇹", name: "Portugal" },
    "QATAR": { code: "QA", flag: "🇶🇦", name: "Qatar" },
    "QA": { code: "QA", flag: "🇶🇦", name: "Qatar" },
    "ROMANIA": { code: "RO", flag: "🇷🇴", name: "Romania" },
    "RO": { code: "RO", flag: "🇷🇴", name: "Romania" },
    "RUSSIA": { code: "RU", flag: "🇷🇺", name: "Russia" },
    "RU": { code: "RU", flag: "🇷🇺", name: "Russia" },
    "RWANDA": { code: "RW", flag: "🇷🇼", name: "Rwanda" },
    "RW": { code: "RW", flag: "🇷🇼", name: "Rwanda" },
    "SENEGAL": { code: "SN", flag: "🇸🇳", name: "Senegal" },
    "SN": { code: "SN", flag: "🇸🇳", name: "Senegal" },
    "SERBIA": { code: "RS", flag: "🇷🇸", name: "Serbia" },
    "RS": { code: "RS", flag: "🇷🇸", name: "Serbia" },
    "SLOVAKIA": { code: "SK", flag: "🇸🇰", name: "Slovakia" },
    "SK": { code: "SK", flag: "🇸🇰", name: "Slovakia" },
    "SLOVENIA": { code: "SI", flag: "🇸🇮", name: "Slovenia" },
    "SI": { code: "SI", flag: "🇸🇮", name: "Slovenia" },
    "SOMALIA": { code: "SO", flag: "🇸🇴", name: "Somalia" },
    "SO": { code: "SO", flag: "🇸🇴", name: "Somalia" },
    "SOUTH KOREA": { code: "KR", flag: "🇰🇷", name: "South Korea" },
    "KR": { code: "KR", flag: "🇰🇷", name: "South Korea" },
    "SPAIN": { code: "ES", flag: "🇪🇸", name: "Spain" },
    "ES": { code: "ES", flag: "🇪🇸", name: "Spain" },
    "SRI LANKA": { code: "LK", flag: "🇱🇰", name: "Sri Lanka" },
    "LK": { code: "LK", flag: "🇱🇰", name: "Sri Lanka" },
    "SUDAN": { code: "SD", flag: "🇸🇩", name: "Sudan" },
    "SD": { code: "SD", flag: "🇸🇩", name: "Sudan" },
    "SWEDEN": { code: "SE", flag: "🇸🇪", name: "Sweden" },
    "SE": { code: "SE", flag: "🇸🇪", name: "Sweden" },
    "SWITZERLAND": { code: "CH", flag: "🇨🇭", name: "Switzerland" },
    "CH": { code: "CH", flag: "🇨🇭", name: "Switzerland" },
    "SYRIA": { code: "SY", flag: "🇸🇾", name: "Syria" },
    "SY": { code: "SY", flag: "🇸🇾", name: "Syria" },
    "TAIWAN": { code: "TW", flag: "🇹🇼", name: "Taiwan" },
    "TW": { code: "TW", flag: "🇹🇼", name: "Taiwan" },
    "TAJIKISTAN": { code: "TJ", flag: "🇹🇯", name: "Tajikistan" },
    "TJ": { code: "TJ", flag: "🇹🇯", name: "Tajikistan" },
    "TANZANIA": { code: "TZ", flag: "🇹🇿", name: "Tanzania" },
    "TZ": { code: "TZ", flag: "🇹🇿", name: "Tanzania" },
    "THAILAND": { code: "TH", flag: "🇹🇭", name: "Thailand" },
    "TH": { code: "TH", flag: "🇹🇭", name: "Thailand" },
    "TUNISIA": { code: "TN", flag: "🇹🇳", name: "Tunisia" },
    "TN": { code: "TN", flag: "🇹🇳", name: "Tunisia" },
    "TURKEY": { code: "TR", flag: "🇹🇷", name: "Turkey" },
    "TR": { code: "TR", flag: "🇹🇷", name: "Turkey" },
    "UGANDA": { code: "UG", flag: "🇺🇬", name: "Uganda" },
    "UG": { code: "UG", flag: "🇺🇬", name: "Uganda" },
    "UKRAINE": { code: "UA", flag: "🇺🇦", name: "Ukraine" },
    "UA": { code: "UA", flag: "🇺🇦", name: "Ukraine" },
    "URUGUAY": { code: "UY", flag: "🇺🇾", name: "Uruguay" },
    "UY": { code: "UY", flag: "🇺🇾", name: "Uruguay" },
    "UZBEKISTAN": { code: "UZ", flag: "🇺🇿", name: "Uzbekistan" },
    "UZ": { code: "UZ", flag: "🇺🇿", name: "Uzbekistan" },
    "VENEZUELA": { code: "VE", flag: "🇻🇪", name: "Venezuela" },
    "VE": { code: "VE", flag: "🇻🇪", name: "Venezuela" },
    "YEMEN": { code: "YE", flag: "🇾🇪", name: "Yemen" },
    "YE": { code: "YE", flag: "🇾🇪", name: "Yemen" },
    "ZAMBIA": { code: "ZM", flag: "🇿🇲", name: "Zambia" },
    "ZM": { code: "ZM", flag: "🇿🇲", name: "Zambia" },
    "ZIMBABWE": { code: "ZW", flag: "🇿🇼", name: "Zimbabwe" },
    "ZW": { code: "ZW", flag: "🇿🇼", name: "Zimbabwe" },
};

export const COUNTRIES: CountryData[] = [
  { code: "", flag: "🌍", name: "Worldwide" },
  { code: "+92", flag: "🇵🇰", name: "Pakistan" },
  { code: "+1", flag: "🇺🇸", name: "United States" },
  { code: "+44", flag: "🇬🇧", name: "United Kingdom" },
  { code: "+1", flag: "🇨🇦", name: "Canada" },
  { code: "+91", flag: "🇮🇳", name: "India" },
  { code: "+971", flag: "🇦🇪", name: "UAE" },
  { code: "+966", flag: "🇸🇦", name: "Saudi Arabia" },
  { code: "+974", flag: "🇶🇦", name: "Qatar" },
  { code: "+968", flag: "🇴🇲", name: "Oman" },
  { code: "+965", flag: "🇰🇼", name: "Kuwait" },
  { code: "+973", flag: "🇧🇭", name: "Bahrain" },
  { code: "+61", flag: "🇦🇺", name: "Australia" },
  { code: "+880", flag: "🇧🇩", name: "Bangladesh" },
  { code: "+86", flag: "🇨🇳", name: "China" },
  { code: "+62", flag: "🇮🇩", name: "Indonesia" },
  { code: "+81", flag: "🇯🇵", name: "Japan" },
  { code: "+60", flag: "🇲🇾", name: "Malaysia" },
  { code: "+977", flag: "🇳🇵", name: "Nepal" },
  { code: "+64", flag: "🇳🇿", name: "New Zealand" },
  { code: "+63", flag: "🇵🇭", name: "Philippines" },
  { code: "+65", flag: "🇸🇬", name: "Singapore" },
  { code: "+82", flag: "🇰🇷", name: "South Korea" },
  { code: "+94", flag: "🇱🇰", name: "Sri Lanka" },
  { code: "+66", flag: "🇹🇭", name: "Thailand" },
  { code: "+84", flag: "🇻🇳", name: "Vietnam" },
  { code: "+43", flag: "🇦🇹", name: "Austria" },
  { code: "+32", flag: "🇧🇪", name: "Belgium" },
  { code: "+359", flag: "🇧🇬", name: "Bulgaria" },
  { code: "+385", flag: "🇭🇷", name: "Croatia" },
  { code: "+420", flag: "🇨🇿", name: "Czech Republic" },
  { code: "+45", flag: "🇩🇰", name: "Denmark" },
  { code: "+358", flag: "🇫🇮", name: "Finland" },
  { code: "+33", flag: "🇫🇷", name: "France" },
  { code: "+49", flag: "🇩🇪", name: "Germany" },
  { code: "+30", flag: "🇬🇷", name: "Greece" },
  { code: "+36", flag: "🇭🇺", name: "Hungary" },
  { code: "+353", flag: "🇮🇪", name: "Ireland" },
  { code: "+39", flag: "🇮🇹", name: "Italy" },
  { code: "+31", flag: "🇳🇱", name: "Netherlands" },
  { code: "+47", flag: "🇳🇴", name: "Norway" },
  { code: "+48", flag: "🇵🇱", name: "Poland" },
  { code: "+351", flag: "🇵🇹", name: "Portugal" },
  { code: "+40", flag: "🇷🇴", name: "Romania" },
  { code: "+7", flag: "🇷🇺", name: "Russia" },
  { code: "+34", flag: "🇪🇸", name: "Spain" },
  { code: "+46", flag: "🇸🇪", name: "Sweden" },
  { code: "+41", flag: "🇨🇭", name: "Switzerland" },
  { code: "+90", flag: "🇹🇷", name: "Turkey" },
  { code: "+380", flag: "🇺🇦", name: "Ukraine" },
  { code: "+54", flag: "🇦🇷", name: "Argentina" },
  { code: "+55", flag: "🇧🇷", name: "Brazil" },
  { code: "+56", flag: "🇨🇱", name: "Chile" },
  { code: "+57", flag: "🇨🇴", name: "Colombia" },
  { code: "+52", flag: "🇲🇽", name: "Mexico" },
  { code: "+51", flag: "🇵🇪", name: "Peru" },
  { code: "+20", flag: "🇪🇬", name: "Egypt" },
  { code: "+254", flag: "🇰🇪", name: "Kenya" },
  { code: "+212", flag: "🇲🇦", name: "Morocco" },
  { code: "+234", flag: "🇳🇬", name: "Nigeria" },
  { code: "+27", flag: "🇿🇦", name: "South Africa" },
  { code: "+93", flag: "🇦🇫", name: "Afghanistan" },
  { code: "+355", flag: "🇦🇱", name: "Albania" },
  { code: "+213", flag: "🇩🇿", name: "Algeria" },
  { code: "+376", flag: "🇦🇩", name: "Andorra" },
  { code: "+244", flag: "🇦🇴", name: "Angola" },
  { code: "+374", flag: "🇦🇲", name: "Armenia" },
  { code: "+297", flag: "🇦🇼", name: "Aruba" },
  { code: "+994", flag: "🇦🇿", name: "Azerbaijan" },
  { code: "+1", flag: "🇧🇸", name: "Bahamas" },
  { code: "+1", flag: "🇧🇧", name: "Barbados" },
  { code: "+375", flag: "🇧🇾", name: "Belarus" },
  { code: "+501", flag: "🇧🇿", name: "Belize" },
  { code: "+229", flag: "🇧🇯", name: "Benin" },
  { code: "+1", flag: "🇧🇲", name: "Bermuda" },
  { code: "+975", flag: "🇧🇹", name: "Bhutan" },
  { code: "+591", flag: "🇧🇴", name: "Bolivia" },
  { code: "+387", flag: "🇧🇦", name: "Bosnia & Herzegovina" },
  { code: "+267", flag: "🇧🇼", name: "Botswana" },
  { code: "+673", flag: "🇧🇳", name: "Brunei" },
  { code: "+226", flag: "🇧🇫", name: "Burkina Faso" },
  { code: "+257", flag: "🇧🇮", name: "Burundi" },
  { code: "+855", flag: "🇰🇭", name: "Cambodia" },
  { code: "+237", flag: "🇨🇲", name: "Cameroon" },
  { code: "+238", flag: "🇨🇻", name: "Cape Verde" },
  { code: "+1", flag: "🇰🇾", name: "Cayman Islands" },
  { code: "+236", flag: "🇨🇫", name: "Central African Republic" },
  { code: "+242", flag: "🇨🇬", name: "Congo - Brazzaville" },
  { code: "+243", flag: "🇨🇩", name: "Congo - Kinshasa" },
  { code: "+506", flag: "🇨🇷", name: "Costa Rica" },
  { code: "+53", flag: "🇨🇺", name: "Cuba" },
  { code: "+357", flag: "🇨🇾", name: "Cyprus" },
  { code: "+253", flag: "🇩🇯", name: "Djibouti" },
  { code: "+1", flag: "🇩🇲", name: "Dominica" },
  { code: "+1", flag: "🇩🇴", name: "Dominican Republic" },
  { code: "+593", flag: "🇪🇨", name: "Ecuador" },
  { code: "+503", flag: "🇸🇻", name: "El Salvador" },
  { code: "+240", flag: "🇬🇶", name: "Equatorial Guinea" },
  { code: "+291", flag: "🇪🇷", name: "Eritrea" },
  { code: "+372", flag: "🇪🇪", name: "Estonia" },
  { code: "+251", flag: "🇪🇹", name: "Ethiopia" },
  { code: "+298", flag: "🇫🇴", name: "Faroe Islands" },
  { code: "+679", flag: "🇫🇯", name: "Fiji" },
  { code: "+241", flag: "🇬🇦", name: "Gabon" },
  { code: "+220", flag: "🇬🇲", name: "Gambia" },
  { code: "+995", flag: "🇬🇪", name: "Georgia" },
  { code: "+233", flag: "🇬🇭", name: "Ghana" },
  { code: "+350", flag: "🇬🇮", name: "Gibraltar" },
  { code: "+299", flag: "🇬🇱", name: "Greenland" },
  { code: "+1", flag: "🇬🇩", name: "Grenada" },
  { code: "+590", flag: "🇬🇵", name: "Guadeloupe" },
  { code: "+1", flag: "🇬🇺", name: "Guam" },
  { code: "+502", flag: "🇬🇹", name: "Guatemala" },
  { code: "+224", flag: "🇬🇳", name: "Guinea" },
  { code: "+245", flag: "🇬🇼", name: "Guinea-Bissau" },
  { code: "+592", flag: "🇬🇾", name: "Guyana" },
  { code: "+509", flag: "🇭🇹", name: "Haiti" },
  { code: "+504", flag: "🇭🇳", name: "Honduras" },
  { code: "+852", flag: "🇭🇰", name: "Hong Kong" },
  { code: "+354", flag: "🇮🇸", name: "Iceland" },
  { code: "+98", flag: "🇮🇷", name: "Iran" },
  { code: "+964", flag: "🇮🇶", name: "Iraq" },
  { code: "+972", flag: "🇮🇱", name: "Israel" },
  { code: "+225", flag: "🇨🇮", name: "Ivory Coast" },
  { code: "+1", flag: "🇯🇲", name: "Jamaica" },
  { code: "+962", flag: "🇯🇴", name: "Jordan" },
  { code: "+7", flag: "🇰🇿", name: "Kazakhstan" },
  { code: "+996", flag: "🇰🇬", name: "Kyrgyzstan" },
  { code: "+856", flag: "🇱🇦", name: "Laos" },
  { code: "+371", flag: "🇱🇻", name: "Latvia" },
  { code: "+961", flag: "🇱🇧", name: "Lebanon" },
  { code: "+266", flag: "🇱🇸", name: "Lesotho" },
  { code: "+231", flag: "🇱🇷", name: "Liberia" },
  { code: "+218", flag: "🇱🇾", name: "Libya" },
  { code: "+423", flag: "🇱🇮", name: "Liechtenstein" },
  { code: "+370", flag: "🇱🇹", name: "Lithuania" },
  { code: "+352", flag: "🇱🇺", name: "Luxembourg" },
  { code: "+853", flag: "🇲🇴", name: "Macau" },
  { code: "+389", flag: "🇲🇰", name: "North Macedonia" },
  { code: "+261", flag: "🇲🇬", name: "Madagascar" },
  { code: "+265", flag: "🇲🇼", name: "Malawi" },
  { code: "+960", flag: "🇲🇻", name: "Maldives" },
  { code: "+223", flag: "🇲🇱", name: "Mali" },
  { code: "+356", flag: "🇲🇹", name: "Malta" },
  { code: "+222", flag: "🇲🇷", name: "Mauritania" },
  { code: "+230", flag: "🇲🇺", name: "Mauritius" },
  { code: "+373", flag: "🇲🇩", name: "Moldova" },
  { code: "+377", flag: "🇲🇨", name: "Monaco" },
  { code: "+976", flag: "🇲🇳", name: "Mongolia" },
  { code: "+382", flag: "🇲🇪", name: "Montenegro" },
  { code: "+1", flag: "🇲🇸", name: "Montserrat" },
  { code: "+258", flag: "🇲🇿", name: "Mozambique" },
  { code: "+95", flag: "🇲🇲", name: "Myanmar (Burma)" },
  { code: "+264", flag: "🇳🇦", name: "Namibia" },
  { code: "+505", flag: "🇳🇮", name: "Nicaragua" },
  { code: "+227", flag: "🇳🇪", name: "Niger" },
  { code: "+507", flag: "🇵🇦", name: "Panama" },
  { code: "+675", flag: "🇵🇬", name: "Papua New Guinea" },
  { code: "+595", flag: "🇵🇾", name: "Paraguay" },
  { code: "+1", flag: "🇵🇷", name: "Puerto Rico" },
  { code: "+250", flag: "🇷🇼", name: "Rwanda" },
  { code: "+685", flag: "🇼🇸", name: "Samoa" },
  { code: "+378", flag: "🇸🇲", name: "San Marino" },
  { code: "+221", flag: "🇸🇳", name: "Senegal" },
  { code: "+381", flag: "🇷🇸", name: "Serbia" },
  { code: "+248", flag: "🇸🇨", name: "Seychelles" },
  { code: "+232", flag: "🇸🇱", name: "Sierra Leone" },
  { code: "+421", flag: "🇸🇰", name: "Slovakia" },
  { code: "+386", flag: "🇸🇮", name: "Slovenia" },
  { code: "+252", flag: "🇸🇴", name: "Somalia" },
  { code: "+211", flag: "🇸🇸", name: "South Sudan" },
  { code: "+249", flag: "🇸🇩", name: "Sudan" },
  { code: "+597", flag: "🇸🇷", name: "Suriname" },
  { code: "+268", flag: "🇸🇿", name: "Eswatini (Swaziland)" },
  { code: "+963", flag: "🇸🇾", name: "Syria" },
  { code: "+886", flag: "🇹🇼", name: "Taiwan" },
  { code: "+992", flag: "🇹🇯", name: "Tajikistan" },
  { code: "+255", flag: "🇹🇿", name: "Tanzania" },
  { code: "+670", flag: "🇹🇱", name: "Timor-Leste" },
  { code: "+228", flag: "🇹🇬", name: "Togo" },
  { code: "+1", flag: "🇹🇹", name: "Trinidad & Tobago" },
  { code: "+216", flag: "🇹🇳", name: "Tunisia" },
  { code: "+993", flag: "🇹🇲", name: "Turkmenistan" },
  { code: "+256", flag: "🇺🇬", name: "Uganda" },
  { code: "+598", flag: "🇺🇾", name: "Uruguay" },
  { code: "+998", flag: "🇺🇿", name: "Uzbekistan" },
  { code: "+58", flag: "🇻🇪", name: "Venezuela" },
  { code: "+967", flag: "🇾🇪", name: "Yemen" },
  { code: "+260", flag: "🇿🇲", name: "Zambia" },
  { code: "+263", flag: "🇿🇼", name: "Zimbabwe" },
];